# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  from_email:
    description: 'sender of the email'
    required: true
  to_email:
    description: 'receiver of the email'
    required: true
  subject:
    description: 'subject of the email'
    required: true
  authorised_username:
    description: 'authorised username for SMTP authentication'
    required: true
  message:
    description: 'message body of the email address'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PASSWORD: ${{secrets.GITHUB_API }}
  args:
    - ${{ inputs.from_email }}
    - ${{ inputs.to_email }}
    - ${{ inputs.subject }}
    - ${{ inputs.authorised_username }}
    - ${{ inputs.message }}